version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: todo_db
    environment:
      POSTGRES_URL: jdbc:postgresql://localhost:5432/todo_db
      POSTGRES_DB: todo_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
